Sol 58058 health actuator
SolaceProducts/solace-spring-cloud pull request #125
Opened 2022-03-02 15:50 UTC by carolmorneau

Includes https://github.com/SolaceProducts/solace-spring-cloud/pull/113 so it should be reviewed/merged before this PR.

2022-03-04 20:22 UTC, Nephery requested changes

2022-03-04 22:05 UTC, Nephery requested changes

2022-03-04 22:05 UTC, Nephery commented on solace-spring-cloud-starters/solace-spring-cloud-stream-starter/README.adoc
> +| Status indicating that the binder is actively trying to reconnect to the message broker.
Add:

```
This is a custom health status. By default, it isn't included in the health severity order list (`management.endpoint.health.status.order`) and returns the default HTTP status code of `200`. To customize these, see https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.health.writing-custom-health-indicators[Writing Custom HealthIndicators].
```

2022-03-04 22:30 UTC, Nephery requested changes
We should add some basic unit testing for `SolaceBinderHealthIndicator` and `SolaceSessionEventHandler` to make sure the session event details get propagated properly and that the `Health` object is correctly constructed. I think mocking the resources for this should be more than good enough to do this.

2022-03-09 21:34 UTC, carolmorneau commented
Retested and works as expected

2022-03-09 21:40 UTC, merged