Spring Boot 3.x Support
SolaceProducts/solace-spring-cloud pull request #224
Opened 2023-05-09 18:57 UTC by mayur-solace

2023-05-10 16:40 UTC, Nephery requested changes

2023-05-10 16:42 UTC, mayur-solace commented on solace-spring-cloud-parent/pom.xml
> +        <solace.jms.version>10.19.1-jakarta_jms.43138</solace.jms.version>
release version is not out yet.

2023-05-10 16:47 UTC, Nephery commented on solace-spring-cloud-stream-binder/solace-spring-cloud-stream-binder-core/src/main/java/com/solace/spring/cloud/stream/binder/properties/SolaceConsumerProperties.java
> -	@Min(1)
Looks like there's jakarta equivalents for validation annotations (e.g. `jakarta.validation.constraints.Min`).
Please add the validation annotations back in.

2023-05-10 16:51 UTC, mayur-solace commented on solace-spring-cloud-stream-binder/solace-spring-cloud-stream-binder-core/src/main/java/com/solace/spring/cloud/stream/binder/properties/SolaceConsumerProperties.java
> -	@Min(1)
Initially plan was to remove both @Min and @PostConstruct. There is any easy way to replace @PostConstruct. So I haven't removed @PostConstruct. I will revert and add @Min back as well. Thanks.

2023-05-11 19:05 UTC, Nephery approved these changes
JCSMP/JMS versions will be updated to release version whenever they come out.

2023-05-11 19:05 UTC, merged